# C4.5

In [1]:
pip install chefboost

Requirement already satisfied: chefboost in c:\users\harry\appdata\local\programs\python\python310\lib\site-packages (0.0.17)
Requirement already satisfied: psutil>=5.4.3 in c:\users\harry\appdata\local\programs\python\python310\lib\site-packages (from chefboost) (5.9.1)
Requirement already satisfied: pandas>=0.22.0 in c:\users\harry\appdata\local\programs\python\python310\lib\site-packages (from chefboost) (1.4.1)
Requirement already satisfied: tqdm>=4.30.0 in c:\users\harry\appdata\local\programs\python\python310\lib\site-packages (from chefboost) (4.64.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\harry\appdata\local\programs\python\python310\lib\site-packages (from chefboost) (1.22.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\harry\appdata\roaming\python\python310\site-packages (from pandas>=0.22.0->chefboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\harry\appdata\local\programs\python\python310\lib\site-packages (from pandas>=0.22.0->chefboost) (2021.3)
Requirement already satisfied: colorama in c:\users\harry\appdata\roaming\python\python310\site-packages (from tqdm>=4.30.0->chefboost) (0.4.4)
Requirement already satisfied: six>=1.5 in c:\users\harry\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas>=0.22.0->chefboost) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
from chefboost import Chefboost as chef

In [7]:
import pandas as pd

df = pd.read_csv("D:\\AML\\tic-tac-toe.csv")

In [8]:
df

    TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]

In [9]:
config = {'algorithm': 'C4.5'}
model = chef.fit(df, config = config, target_label = 'class')

[INFO]:  6 CPU cores will be allocated in parallel running
WARNING: You set the algorithm to  C4.5  but the Decision column of your data set has non-object type.
That's why, the algorithm is set to Regression to handle the data set.
Regression  tree is going to be built...
-------------------------
finished in  9.229725122451782  seconds
-------------------------
Evaluate  train set
-------------------------
MAE:  0.06280445372303411
MSE:  0.031402226861517016
RMSE:  0.1772067348085761
RAE:  0.21921779814717166
RRSE:  0.37238272358380264
Mean:  0.6534446764091858
MAE / Mean:  9.611288604898832 %
RMSE / Mean:  27.118858138437044 %

In [10]:
df

    TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]

In [11]:
prediction = chef.predict(model, param = ['x','x','x','x','o','o','x','o','o'])

In [12]:
prediction

True

In [13]:
prediction = chef.predict(model, param = ['x','x','x','o','o','o','x','o','x'])
prediction

True

In [14]:
prediction = chef.predict(model, param = ['o','o','o','x','o','x','x','x','o'])
prediction

False